### PR TITLE
Fix Infrastructue typo

### PR DESCRIPTION
**Pull request by d-m-u**

### CODE REVIEW

**Comment by suyogsainkar** [comment]
It seems like this MR is a duplicate of https://github.com/ManageIQ/manageiq_docs/pull/1103
Closing MR.

**Comment by d-m-u** [comment]
@suyogsainkar is it? It's a different file.

**Comment by d-m-u** [comment]
I don't think this should be closed? There's still a typo on https://github.com/ManageIQ/manageiq_docs/search?q=Infrastructue&unscoped_q=Infrastructue

**Comment by suyogsainkar** [comment]
@d-m-u Sorry, re-opening and merging now.

**Pull request merged**
