### PR TITLE
Reformatted SAML section to clarify RH SSO specific content

### PR DESCRIPTION
**Pull request by dayleparker**
Reformatted SAML section to make it more clear that the config procedure is for RH SSO, while the other parts are generic. Also a few small terminology edits to keep consistent with other docs.

### CODE REVIEW

**Comment by dayleparker** [comment]
Hi @jvlcek, please let me know your thoughts on these changes. Thanks for your help on the VIP question :)

**Comment by jvlcek** [comment]
LGTM

**Comment by cbudz** [comment]
Hey Dayle, all updates look good. Merging this request.

**Comment by dayleparker** [comment]
Thanks Chris!

**Pull request merged**
