### PR TITLE
update managing_providers downstream references

### PR DESCRIPTION
**Pull request by CarlosGlez7**
I had several doubts with the "Red Hat" word. I added a file called "doubts" where you can find the problems that I talk about.

### CODE REVIEW

**Comment by Fryguy** [comment]
There is some really weird stuff going on with the history here...I think you might have accidentally broke an old commit (see the first one where the commit has like a partial PGP signature).

**Comment by alexvkcr** [comment]
The reason why the history is appearing differently is we had to roll back a commit and as of that moment, the history of commits appears in each upload. 

There is no conflict with files according to GitHub so it's possible to keep working and we're ready to respond to commentaries and correct errors in our uploads.

If it's requested we reupload changes so it appears differently, we will do so.

@Fryguy @CarlosGlez7 @katafira @sergio-ocon @delaluzparra

**Comment by Fryguy** [comment]
> There is no conflict with files according to GitHub so it's possible to keep working and we're ready to respond to commentaries and correct errors in our uploads.

There isn't a literal merge conflict, but if you look at the Files Changed tab it contains all of the changes from all of those historical commits, which makes it hard to review.

---

commit a6a8a60 (from this PR) is an accidental rewrite of commit e6bb1d38.  By rewriting the commit it creates a new history.  Here it what the history looks like in this PR (I've snipped out some of the common commits in both histories for brevity).

```text
* b2bdb1b - (HEAD -> pull_request_31) update managing_providers (5 days ago) <root>
*   85a2cc2 - Merge pull request #19 from elladeon/master (5 weeks ago) <Jason Frey>
|
| ****SNIP****
|
*   b69bd9b - Merge pull request #9 from abellotti/auth_asciibinder (6 months ago) <Jason Frey>
|\
* \   7b335d2 - Merge pull request #8 from psav/patch-1 (6 months ago) <Jason Frey>
|\ \
| * | a6a8a60 -  iQEcBAABAgAGBQJWN+BkAAoJEJGWkypDEpFJcRQH/i+LHwiqc1HKxctqtH3TR2tX  vKYyhL77pTbXVOl5iN5rDgQud9LAPG8Pl/47G99dSyRhL77MD/UfPc64EYRpA5Yz  OIdUi1GT35fDOvuyUPPOdzeKHx8tXkcwTuSR3RLsqNn/NzAbTkLUKM/GQvNr6AQT  Zk9cazjOuy6bhyiCY00+iH/ieNlJxfyfSeQbXKGQrd65ufBVbulx/RUyJfM8ORqg  5lLhvqVh01XNyoLcp170jrjPq
|/ /
| | *   840b8cb - (upstream/master, master) Merge pull request #18 from abellotti/auth_saml (8 days ago) <Marianne Feifer>
| | |\
| | | * 5f91ae0 - PR Review Changes: (8 days ago) <Alberto Bellotti>
| | | * 6abe851 - [auth] Adding SAML Configuration documentation (9 days ago) <Alberto Bellotti>
| | * |   eb4da24 - Merge pull request #20 from skateman/cfme-to-manageiq (9 days ago) <Jason Frey>
| | |\ \
| | | |/
| | |/|
| | | * 4982bcd - Renamed cfme in configuration files to manageiq (5 weeks ago) <Dávid Halász>
| | |/
| | *   eddf88c - Merge pull request #19 from elladeon/master (5 weeks ago) <Jason Frey>
| | |
| | | ****SNIP****
| | | 
| | *   610c005 - Merge pull request #9 from abellotti/auth_asciibinder (6 months ago) <Jason Frey>
| | |\
| | |/
| |/|
| * | 885d7a4 - [auth] AsciiBinder updates (6 months ago) <Alberto Bellotti>
|/ /
| *   3a7adc0 - Merge pull request #8 from psav/patch-1 (6 months ago) <Jason Frey>
| |\
|/ /
| * e6bb1d3 - Updated provisioning types for API (6 months ago) <Pete Savage>
|/
* d3a365a - (tag: capablanca-1-rc1, upstream/capablanca, origin/capablanca) Add capablanca branch (6 months ago) <Jason Frey>
```

To fix, I think the simplest thing to do is just cherry-pick the one *actual* commit onto master...you can try this:

```bash
# Assuming your upstream remote pointing to ManageIQ/manageiq_docs is named "upstream"
git checkout carlos-3
git fetch --all
git reset --hard upstream/master
git cherry-pick b2bdb1b
git push -f
```

**Comment by alexvkcr** [comment]
How was the result @Fryguy ?

Is it easier to work with now? if so, we'll implement it in the rest of PRs

**Comment by CarlosGlez7** [comment]
Closing PR, changes were added to #48

**Pull request closed without merging**
