### PR TITLE
BZ1420206 - Fixes to "Reintroducing the failed node"

### PR DESCRIPTION
**Pull request by dayleparker**
Hi Suyog,
I've made a lot of changes to 3.3. Reintroducing the Failed Node following feedback from a customer case. This also resulted in some more steps being added in to the installation procedures, plus a note about time synch in the Requirements chapter.

Would you mind having a look and letting me know if you spot anything confusing or needing a fix?
http://file.bne.redhat.com/~dayparke/CloudForms/HAfailednode-3/build/tmp/en-US/html-single/

Thanks so much,
Dayle

### CODE REVIEW

**Comment by dayleparker** [comment]
Suyog, let's wait to merge this one until we reach a concensus on the reboot in https://bugzilla.redhat.com/show_bug.cgi?id=1420206#c10. Thanks for pointing out the new comment!

**Comment by dayleparker** [comment]
Hi @suyogsainkar,
It looked like a change to the 'reboot appliance' step in the last procedure of the guide was what was required. I've made this fix, and it is ready for your review.
Please let me know if you have any feedback :)
Thanks so much!
Dayle

**Comment by suyogsainkar** [comment]
@dayleparker Hi Dayle, thanks for incorporating all feedback items into the doc - looks great! Just a couple of optional suggestions below:

1. In 2.5. Configuring the Standby Database Appliance
"Select y to configure Replication Manager for automatic failover." > replication manager (there's another instance which is in lower case)

2. In 3.3. Reintroducing the Failed Node, 
Step 5.
"If the **follow** command times out..." > "If the **repmgr standby follow** command times out..." 

3. In 2.3. Installing a Standard Red Hat CloudForms Appliance
Step 8. sub step c.: "Note that creating a database region will destroy any existing data and cannot be undone."
Perhaps, worth converting this into a note box? 

Please let me know what you think.

Cheers,
Suyog

**Comment by dayleparker** [comment]
Hi @suyogsainkar,

Thanks for the review! Your suggestions make sense to me -- I've made all those changes (I made the Note an Important box as it's pretty serious). Please let me know if you spot anything else, or it's ready to merge.

Cheers,
Dayle

**Comment by suyogsainkar** [comment]
Awesome, thanks for making those changes, Dayle! Merging to master.

**Pull request merged**
