### PR TITLE
Remove references to MiqPassword

### PR DESCRIPTION
**Pull request by Fryguy**
@adahms Please review.  We are removing MiqPassword in favor of ManageIQ::Password moving forward.

cc @jrafanie

### CODE REVIEW

**Comment by Fryguy** [comment]
@cbudz ?

**Comment by cbudz** [comment]
@Fryguy what versions is this change applicable to?

**Comment by Fryguy** [comment]
I-release

**Comment by cbudz** [comment]
Thanks @Fryguy. Merging this request.

**Pull request merged**
