### PR TITLE
Use updated retirement calls for service retirement 

### PR DESCRIPTION
**Pull request by d-m-u**
Pretty sure that this call will 💣 on anything recent.

I'm pretty sure there are more of these to fix but it has to be in follow-up

### CODE REVIEW

**Comment by suyogsainkar** [comment]
Thanks @d-m-u . Does this apply to I & H versions?
cc: @jhoyt-rh can you cherry-pick once confirmed / merged.

**Comment by d-m-u** [comment]
@suyogsainkar when you were here, we discussed how these changes went into everything past the gap release

**Comment by suyogsainkar** [comment]
@d-m-u oh, right. thanks for the reminder. merging now.

**Comment by jhoyt-rh** [comment]
@suyogsainkar SO, this is to be cherry-picked to Ivanchuk and Hammer, right?

**Pull request merged**
