### PR TITLE
Bz#1476283 Enabling AWS events

### PR DESCRIPTION
**Pull request by dayleparker**
Added new procedure on enabling Amazon events.

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by dayleparker** [comment]
Hi Suyog,

This is all ready for your peer review now. Please let me know if the content makes sense, or if it needs any changes. Also I'm not sure if I documented the Amazon side of things too in-depth, what do you think? I want these instructions to be useful, but also not too specific in case the AWS UI gets updated.

Preview link and my testing screenshots (as we discussed) in https://bugzilla.redhat.com/show_bug.cgi?id=1476283#c15

Many thanks,
Dayle

**Comment by suyogsainkar** [comment]
@dayleparker Hi Dayle, thanks for making these updates - the content reads well and makes sense to me. I understand most of these steps are on the AWS side but I agree it's all useful to the user. Merging to master. Thanks, Suyog

**Comment by dayleparker** [comment]
Thanks so much @suyogsainkar! I really appreciate your thorough review on this. :)

**Pull request merged**
