### PR TITLE
Fix pods documentation

### PR DESCRIPTION
**Pull request by bdunne**
- Remove appliance console references
- Add documentation for configuring custom SSL certificates

https://bugzilla.redhat.com/show_bug.cgi?id=1473957

### CODE REVIEW

**Comment by bdunne** [comment]
@miq-bot add_reviewer @carbonin 
@miq-bot add_label gaprindashvili/yes

**Comment by bdunne** [comment]
@miq-bot add_labels gaprindashvili/yes

**Comment by dayleparker** [comment]
Thanks @bdunne for the updates, and @carbonin for the CC.

@bdunne, the content looks great, thanks for the update. I just made a few Asciidoc markup/styling updates so it's formatted like the other parts of the guide. Please let me know if it looks OK with you (or make any changes), and I'll merge.

**Comment by bdunne** [comment]
:+1: LGTM  Thanks @dayleparker !

**Pull request merged**
