### PR TITLE
Added the missing prerequisite steps for installing CF on AWS

### PR DESCRIPTION
**Pull request by suyogsainkar**
BZs: https://bugzilla.redhat.com/show_bug.cgi?id=1553557
https://bugzilla.redhat.com/show_bug.cgi?id=1536821

Preview: http://file.bne.redhat.com/ssainkar/install-cf-on-aws/html-single/#uploading-the-appliance-on-amazon-ec2

### CODE REVIEW

**Comment by suyogsainkar** [comment]
Hi Dayle,
Thanks for your review and useful suggestions. Accordingly, I've made changes for better flow and readability. 
-Re. your question about the workflow - those config steps on Amazon are performed after you upload the appliance to an Amazon S3 bucket. Create the bucket and VM Import Service Role first, then upload the appliance, and perform those config steps before importing the appliance. Therefore, the step about the requirement for creating an Amazon S3 bucket was listed there and then the config steps. That said, I've applied structural changes and modified the related section titles so that it's clearer. 
-Also, I've removed the line "Depending on your infrastructure, allow time for the upload." as I don't think it adds much value. 
Please let me know what you think.
Thanks,
Suyog

**Comment by dayleparker** [comment]
Hi Suyog,
Thanks for making those fixes! The content reads well. My last remaining question relates to "RHN credentials" -- I left a comment on the code. I  would have just gone and fixed the "RHN" but I'm not sure what asciidoc conditionalization is needed... :( What do you think?
Cheers,
Dayle

**Comment by suyogsainkar** [comment]
@dayleparker Hi Dayle, no worries - I've modified the step to clarify on registry.access.redhat.com credentials, and also conditionalized it for upstream. Thanks.

**Comment by dayleparker** [comment]
Thanks @suyogsainkar! Looks good to me :) Merging.

**Comment by suyogsainkar** [comment]
Thanks, Dayle! I've backported updates to the G and F branch.

**Pull request merged**
