### PR TITLE
Re-worded the note about required permissions for OSP infrastructure …

### PR DESCRIPTION
**Pull request by adahms**
…providers.

### CODE REVIEW

**Comment by aufi** [comment]
Thanks for the PR @adahms. I have just a comment that this affects only Openstack Cloud provider when using Keystone v3 auth (no Openstack Infrastrusture provider). Could it be updated?

**Comment by aufi** [comment]
@adahms Looks good to me now, thanks!

**Comment by Fryguy** [comment]
@adahms Just as an FYI, please avoid creating branches on the main repo, and instead create it on your fork.  I'm sure it was just an accident, but just wanted to give you a heads up.

**Comment by adahms** [comment]
@aufi Thank you - I'll go ahead and merge it.

**Comment by adahms** [comment]
@Fryguy Sorry, Jason - my bad. I'll keep that in mind for future work.

**Pull request merged**
