### PR TITLE
Add Methods Available for Automation Guide

### PR DESCRIPTION
**Pull request by kallimachos**

### CODE REVIEW

**Comment by mfeifer** [comment]
The TOC is great and most things look great.  However, the hyperlinks in the Methods Hierarchy section don't work.

**Comment by kallimachos** [comment]
I've fixed the XREF links.  Hopefully everything works as expected now.

**Comment by geertj** [comment]
@kallimachos There was a question on this on the miq.talk. I added a small reply maybe you can add some more information?

http://talk.manageiq.org/t/documentation-as-html/582/2

**Comment by johnmark** [comment]
This looks nice. Is it ready to merge?

**Comment by mfeifer** [comment]
I just want to check in with  @tinaafitz to make sure we're covered.

**Comment by tinaafitz** [comment]
@mfeifer 
It looks good.

**Comment by Fryguy** [comment]
Wherever it says ManageIQ, should it say something like `{product_name}` so that the docs are for both products?

**Comment by mfeifer** [comment]
@Fryguy is there something you can do programmatically to make that happen?  We really want to get this published.  @johnmark can we discuss at sync call?

**Comment by Fryguy** [comment]
What do you mean? It's built in... Read the  Readme for how.   If it's not
working let me know.

**Comment by Fryguy** [comment]
Oh lol... That one thing is not in the Readme specifically.   @nhr can you comment here?  Perhaps the  Readme on the openshift  docs needs some updating here.   I'm not  100% sure here and is been a few months since I've been in this code

**Comment by Fryguy** [comment]
Actually,  @nhr can you review this given your expertise on the  openshift side?  Perhaps you can see any problems we may not understand yet. 

@mfeifer how can we publish yet anyway?  I haven't updated the header to remove openshift specifics.

**Comment by mfeifer** [comment]
@Fryguy I meant merge, not publish.  Sorry.  :tulip:

**Comment by nhr** [comment]
It looks like you are using `{product-title}` and `{product-version}` in the metadata at the top of your docs. These placeholders can be used anywhere in the docs and they will be replaced.

That said - @Fryguy we should sync up because the openshift-docs generator has evolved a bit since our last discussion and you may want to take advantage of the improvements.

**Comment by Fryguy** [comment]
@kallimachos Please change all references to ManageIQ to `{product-title}`

**Pull request merged**
