### PR TITLE
[EUWE] Added/modified config steps and conceptual info about tenancy

### PR DESCRIPTION
**Pull request by suyogsainkar**
Documented additional info on tenancy in the Deployment Planning guide based on CF 4.1 internal enablement session[1], also made a few modifications in the General Configuration guide.

Preview: file.bne.redhat.com/ssainkar/Red_Hat_CloudForms-4.2-Deployment_Planning_Guide-en-US-tenancy-updated.pdf

[1]https://drive.google.com/file/d/0BwP6GDc9bTQ5WFF0cnRlZGc5SDA/view
https://docs.google.com/presentation/d/11_c-l34NgcBcM7DID9dRwlA21YU9vHSCsc4WavFfRmA/edit#slide=id.g10b88e9372_4_74

### CODE REVIEW

**Comment by dayleparker** [comment]
Hi Suyog,

The new section on tenancy looks really great, and gives a nice clear picture of what the feature is in CloudForms and how to use it. It also answers the questions Jared's customer has asked in Comment 0 (though it might be worthwhile getting the customer’s feedback on it after it’s published too :) 

The new section looks close to ready to be published, with the exception of a few smallish fixes. I’ve marked my comments as [Suggestion] and [Fix] so you can more easily decide how to address the list below:

Apologies for the long list! Please let me know if you have any questions, or want to discuss any of my feedback. Way to describe this complicated feature in detail! :) 
Cheers,
Dayle

===
[Suggestion] “It allows for siloed organizations that have separate authentication and users, different branding, and different security." -> could use some wording tweaks to be more specific: Maybe: "It allows for MANAGEMENT OF siloed organizations that have separate authentication and users, different branding, and different security SETTINGS."

[Fix] This paragraph is difficult to read: "Besides, tenants can also have projects as children. A project is a self-contained tenant, that is it cannot have a child tenant, and is useful to allocate resources to a small group or team within a larger organization."
Remove “besides”, as the word doesn’t fit here.
Perhaps italicize "project" at first mention? Is it possible to define projects first in this paragraph, something like:
"A tenant can also contain a self-contained child tenant known as a project. A project cannot have a child tenant, but is useful to allocate resources to a small group or team within a larger organization."

[Fix] The Note starting "If you choose..." needs punctuation and perhaps replacing "everything" with something more specific (I can't think of a word atm) -- what is "everything" referring to?
Perhaps reword a little: "If you do not add any additional tenants, everything is contained in a single base tenant, which is your CloudForms appliance itself. In CloudForms, this is sometimes referred as tenant zero."

[Suggestion] Would it be more clear to refer to Tenant administrator and Tenant quota administrator as ‘account roles’, to differentiate between server roles/account roles? When I read it, I went looking for the roles first in the Server Roles part of the UI. Alternatively, maybe this could be better solved by adding a link to https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.2/html-single/general_configuration/#roles in the section "In CloudForms, the following two roles are associated with tenancy:". What do you think? Maybe that bit of info should also have a heading, like “Tenancy Account Roles” as well so the text is easy to find if skimming.

[Fix] - Missing word. Add "and" to "These roles are not limited to the tenant upon which they are acting and act across all tenants, AND therefore should be considered privileged users." I would also recommend deleting "Keep in mind" to minimize colloquialism.

[Suggestion] In "Tenantless", I'd recommend rewording "Similar to the previous system" to be more specific, or even noting the last version of CloudForms without tenancy (was it introduced in 4.0?), ie. something better written/shorter than the following: "Similar to CloudForms versions prior to 4.0, which did not contain tenancy support". Or maybe leave that part of the sentence out if it’s too hard to reword. Also, would you *create* a single large tenant, or is this the default CloudForms configuration, as explained earlier in the note about ‘tenant zero’? If it’s true, would it be worthwhile mentioning that here?

[Fix] Typo in "Enterprise model" - scenarios => change to scenario

[Fix] Typo in "Tenancy Configuration" - setup ==> "set up". Also, that first sentence might be more clear and minimal reworded as something like: "You can configure tenancy from the CloudForms user interface by selecting Configuration from the settings menu, and then clicking on the Access Control accordion."

[Fix] Typo in "Tenancy in Automation", please remove the comma after "such as," ==> so it is "such as if you have:"

[Suggestion] Remove "to tackle" (colloqualism) -- this line reads better in the list without it

[Suggestion] Remove "some" from "some departments" -- this line works better in the list without it

[Fix] Missing word. Add "a" to the last list entry (for list agreement) so it's "a customer who is a holding company or centralized IT organization for managing different business units"

[Fix] Typo. domain => domains "Note that just like standard domains are nested," (I recommend starting the sentence with "Just like standard domains are nested," as well)

[Fix] Typo. "You can allocate and enforce quotas for the following attributes." should end with a colon, instead of a full stop.

[Fix?] I can't find a section called "Managing Tenant and Project Quotas" in the Gen Config guide - should this link be corrected?

[Fix] Typo. Missing comma in "Monitoring Alerts, and Reporting guide" ==> "Monitoring, Alerts, and Reporting guide"

[Suggestion] The example report screenshot is a great idea, and really handy! However, I think it would be good to introduce what we are showing the reader, either with a short "The following example shows a tenant quota report", or even just editing the header "Example" with a bit more detail. What do you think?

[Suggestion] "In Use: Amount currently in use by tenants" -- maybe make it a little more specific like "In Use: Amount of quota currently in use by tenants"

[Fix] I'm a bit confused about what this note is saying: "You will see in the report all of the tenants but there is no nesting information available yet." Can it be reworded and explained? Or just deleted?

[Fix] Typo. Missing "s" in "catalogs" ==> "Similar to automate domains, you can have service catalogs at each level of tenancy"

[Fix]  For clarity - "Once added, it is visible to any child or lower tenants," ==> "Once added, a provider is visible to any child or lower tenants,"

[Suggestion] Should section “2.4 EXAMPLE POSTGRESQL CONFIGURATION FILE “be moved into 2.3 Centralized Admin as a subsection? (Or elsewhere?) It seems to be floating in an odd spot now, with the tenancy section in its current position.

[Suggestion] There's a couple mentions of "and related procedures", which could probably be removed without harm.

**Comment by suyogsainkar** [comment]
@dayleparker Hi Dayle, many thanks for your thorough review and suggestions, and my apologies for the delayed response. I've fixed the typos and implemented all your suggestions.
Regarding -
-"Managing Tenant and Project Quotas" in the Gen Config guide, I've retitled a section there as part of this MR itself, which is why you may not have found it. :) 
-“2.4 EXAMPLE POSTGRESQL CONFIGURATION FILE - This section is definitely out of place and I'm going to move it to a more suitable spot as part of the Deployment Planning restructuring bug/MR shortly.
Please let me know what you think and if you spot anything else that needs fixing, otherwise I think it's ready to be merged.
Thanks!
Suyog

**Comment by adahms** [comment]
@suyogsainkar @dayleparker - Sorry to butt in, but I just wanted to respond to the test result comments from miq-bot.

We'll need to conditionalize the links included in these sections so that they only appear in the downstream. Simple, one line conditions along the lines of 'cfme::[<link>]' should do.

Let me know if you have any questions.

**Comment by suyogsainkar** [comment]
@adahms Hi Andrew, thanks for your comment! I've conditionalized the links included in these sections so that they only appear in the downstream. @dayleparker It's all ready for your final review. :) Thanks!

**Comment by dayleparker** [comment]
Hi Suyog,
Thanks for making all of those changes! (And for clarifying about the Managing Tenants and Project Quotas section). I think the content looks excellent. A few last fixes though...

In doc-Deployment_Planning_Guide/topics/planning.adoc:

I spotted one typo in this note (extra "to" and can't get in to fix it for some reason -- would you mind fixing that so I can merge?  (It should start with "If you do not add any additional tenants,")

> If you do not to add any additional tenants, all resources and user accounts are contained in a single base tenant which is your {product-title_short} appliance itself. In {product-title_short}, is sometimes referred as 'tenant zero'.

Also, while you're in there, I have realized one of the wording suggestions I gave you before sounds a bit funny. What do you think of changing "to allocate" ==> "for allocating" in the following sentence? I think it might read a tiny bit better. What do you think?

> "A tenant can also contain a self-contained child tenant known as a 'project'. A project cannot have a child tenant, but is useful **to allocate** resources to a small group or team within a larger organization."

Also, just looking at the changes to "doc-General_Configuration/topics/Configuration.adoc" -- I think "Quota" should be plural (Quotas) in this title:

> Managing Tenant and Project Quota

Thanks for making those last two fixes -- everything looks good to merge after that.

And in the line "Select the tenant or project then click *Policy*," -- there should be a comma after "project".

Thanks Suyog!
Cheers,  
Dayle

**Comment by suyogsainkar** [comment]
@dayleparker Cool - all fixed and ready to merge. Thanks again!

**Comment by dayleparker** [comment]
Awesome, thanks Suyog!

**Pull request merged**
