### PR TITLE
update retirement calls

### PR DESCRIPTION
**Pull request by d-m-u**
use retirement as a request calls instead of the older retirement calls

### CODE REVIEW

**Comment by abellotti** [comment]
The API currently supports both, retire and request_retire.  Documentation should reflect this.

**Comment by d-m-u** [comment]
Then we should make it clearer in these docs what the differences between the two are because I keep fixing bugs where people are using the wrong call.

**Comment by abellotti** [comment]
That's fine, unless we are going to throw away/deprecate the old one, let's document both and clearly describe the difference.

**Comment by d-m-u** [comment]
Alright but I would have thought that for this overview page especially we'd at least have examples that are up-to-date. Since the only reason we still have the old call is backwards compatibility and everything else is using the request call, it isn't really user-friendly to be using the old example here.

**Comment by abellotti** [comment]
Ok, if the old one is kept around for compatibility, then we could deprecate it at some point.  Then, yes, let's just document request_retire. 👍

**Comment by d-m-u** [comment]
Deprecating it would break retirement for any pre-Hammer state machine, which is why I think we don't want to deprecate it. But since its functionality has that limit, I do think these docs for any relevant release should be using the request call.

**Pull request merged**
