### PR TITLE
Update of monitoring, alerts and reporting to delete downstream references

### PR DESCRIPTION
**Pull request by sergio-ocon**
I've updated the documentation so now no references are done to downstream.

Changes still to be done:
- I used if/else branches where it was not possible to completely change references.
- Some of those references are links to documentation  so they should updated for MiQ
- I've used an if/else to delete a reference to support, verify the altenrative text

Regards,
Sergio

### CODE REVIEW

**Comment by sergio-ocon** [comment]
@elladeon Could you review this? Thanks

**Comment by katafira** [comment]
Default operations performed over all Pull Request of this team
-Downcased names of files
-Changed 'Red Hat CloudForms', 'CloudForms' ,'Cloudforms' ,'Cloudforms Management Engine' ,'CFME' with {product-title} 
-Changed '4.0' with {product-version} 
-Removed references to  '4.x' ,'3.x' ,'3.1' ,'3.2'

Specific commentaries of this PR:
Issue: Do I have to change Red Hat Support in any way or should I just leave it as it is?
*************************************************************************************************************
/monitoring_alerts_and_reporting/topics/to_create_a_real_time_performance_alert.adoc:
   24    Otherwise, choose from the possible trending options.
   25  * In *Field Meets Criteria for*, select the amount of time that the threshold requires to be met to trigger the alert.
   26: * Set *Debug Tracing* to true only when directed to do so by Red Hat Support.
   27    This provides an extremely detailed level of logging and can result in many more log lines being written.
   28  


/home/kata/manageiq_docs_fork/manageiq_docs/monitoring_alerts_and_reporting/docinfo.xml:
    1  <title>Monitoring, Alerts, and Reporting</title>
    2: <productname>Red Hat CloudForms</productname>
    3  <productnumber>4.1-Beta</productnumber>
    4  <subtitle>Creating and managing reports, feeds, and widgets in {product-title}</subtitle>

/home/kata/manageiq_docs_fork/manageiq_docs/monitoring_alerts_and_reporting/metadata.ini:
    6  [metadata]
    7  title = Monitoring Alerts and Reporting
    8: product = Red Hat CloudForms
    9  version = 4.1
   10  edition = 

/home/kata/manageiq_docs_fork/manageiq_docs/monitoring_alerts_and_reporting/topics/to_create_a_real_time_performance_alert.adoc:
   24    Otherwise, choose from the possible trending options.
   25  * In *Field Meets Criteria for*, select the amount of time that the threshold requires to be met to trigger the alert.
   26: * Set *Debug Tracing* to true only when directed to do so by Red Hat Support.
   27    This provides an extremely detailed level of logging and can result in many more log lines being written.
   28     
*************************************************************************************************************
											*********

											
******************************************** WARNING ********************************************************

WARNING: Since I have to change all file names and folder names lo lowercase, I also changed the links in several files to match the new names. 

*************************************************************************************************************


@alexvkcr @delaluzparra @sergio-ocon

**Comment by mfeifer** [comment]
@elladeon @Fryguy  does this look right to you?

**Comment by Fryguy** [comment]
Closing in favor of #62

**Pull request closed without merging**
