### PR TITLE
Unifying files

### PR DESCRIPTION
**Pull request by apinnick**
Unified the conversion host modules and tagged the variations.

Formatted doc sections for 1.1:
http://file.tlv.redhat.com/~apinnick/IMS_1.1_unifying_files/#Configuring_conversion_hosts_ansible_rhv_1-1_vddk

http://file.tlv.redhat.com/~apinnick/IMS_1.1_unifying_files/#Configuring_environment_for_ssh_transformation_rhv_1-1_ssh

http://file.tlv.redhat.com/~apinnick/IMS_1.1_unifying_files/#Configuring_conversion_hosts_ansible_osp_1-1_vddk

http://file.tlv.redhat.com/~apinnick/IMS_1.1_unifying_files/#Configuring_environment_for_ssh_transformation_osp_1-1_ssh

Formatted doc sections for 1.2:

http://file.tlv.redhat.com/~apinnick/IMS_1.2_unifying_files/#Configuring_conversion_hosts_cloudforms_rhv_1-2_vddk

http://file.tlv.redhat.com/~apinnick/IMS_1.2_unifying_files/#Configuring_environment_for_ssh_transformation_rhv_1-2_ssh

http://file.tlv.redhat.com/~apinnick/IMS_1.2_unifying_files/#Configuring_conversion_hosts_cloudforms_osp_1-2_vddk

http://file.tlv.redhat.com/~apinnick/IMS_1.2_unifying_files/#Configuring_environment_for_ssh_transformation_osp_1-2_ssh

### CODE REVIEW

**Comment by apinnick** [comment]
@cbudz 

Could you please review this PR? Thanks

**Comment by cbudz** [comment]
Hi,

Overall I think this enhances the user experience and looks great. Just a few comments as I was reading through each section:

IMS 1.1:

-  2.2.2. Installing and configuring Red Hat Virtualization - "+" character appearing between note admonitions.

- 2.3.2. Configuring the conversion hosts for VDDK transformation - Prerequisite section notes the **conversion_host_disable** playbook run and command with the absolute path to the playbook, but it might be more user friendly to include some information in its own section about playbooks bundled with CloudForms that you'd use in the migration process and where to find them. Also do any parameters need to be changed ever? Or are the playbook run as-is? 

IMS 1.2:

- 2.3.2. Configuring the conversion hosts for VDDK transformation - prerequisites section notes checking the validity of subscriptions for hosts. Is this performed on the RHV machine? I might specify exactly where the user is running this command.

**Comment by apinnick** [comment]
@cbudz 

>     * 2.2.2. Installing and configuring Red Hat Virtualization - "+" character appearing between note admonitions.

Sorry -- lots of missing tags! I forgot that I extended the context but didn't update all of the module tags. Fixed.

>     * 2.3.2. Configuring the conversion hosts for VDDK transformation - Prerequisite section notes the **conversion_host_disable** playbook run and command with the absolute path to the playbook, but it might be more user friendly to include some information in its own section about playbooks bundled with CloudForms that you'd use in the migration process and where to find them. 

Playbooks are bundled with RHV, not CF. There is no section about the playbooks because there are only 2. But I could put the migration playbook in its own section. I had it in its own section (or maybe it was a note) originally because it's so short.

>Also do any parameters need to be changed ever? Or are the playbook run as-is?

Just run as-is. Doesn't need parameters because it just undoes all the conversion host configuration on whatever RHV host it's being run on.

>     * 2.3.2. Configuring the conversion hosts for VDDK transformation - prerequisites section notes checking the validity of subscriptions for hosts. Is this performed on the RHV machine? I might specify exactly where the user is running this command.

It's performed on the RHV host. There are RHV hosts and RHV engine (RHVM or RHV Manager). I guess I could add that, since the conversion host config for 1.2 is in the UI and not on the command line, like in 1.1.

**Comment by apinnick** [comment]
@cbudz  

I've looked at the conversion-host-disable playbook instructions again. I think I would like to leave it under prerequisites and not move it to a separate section, for two reasons: 

(1) It is a prerequisite, since it has to be run if the conversion host has been configured in the past.
(2) It is so short (one step) that I don't see any point in giving it its own section.

**Comment by cbudz** [comment]
Thanks for the feedback. LGTM. Merging this PR.

**Pull request merged**
