### PR TITLE
Restructure appliance upload instructions - darga

### PR DESCRIPTION
**Pull request by dayleparker**
Hi Suyog,

This PR contains a restructure of the uploading an appliance for the different RHV/RHEV versions.
I also changed the naming of RHEV to RHV throughout, except where it's specifically talking about RHEV 3.6.

Preview: http://file.bne.redhat.com/~dayparke/CloudForms/RHV-upload-methods/build/tmp/en-US/html-single/

Can you please review and merge the changes? Let me know if you have any feedback.

Thank you,
Dayle

### CODE REVIEW

**Comment by suyogsainkar** [comment]
@dayleparker Hi Dayle, thanks for the PR. The restructuring of the uploading an appliance for the different RHV/RHEV versions looks good to me - nice work! Just two small suggestions:

1. I think in the following instances **OVF** should be changed to **OVA**. (In the actual examples we have used an .ova file) 
   - last line of section 1.2.2. Uploading the Appliance with the Image Uploader
"Once the OVF is uploaded and imported as a template, add a network adapter to the template itself."
   - Section 1.2.3 Uploading the Appliance Manually, steps 3 and 4.

2. (Optional) In the first para of Chapter 1. Installing Red Hat CloudForms: "After downloading Red Hat CloudForms as a virtual machine image template from the Red Hat Customer Portal, the installation process takes you through the steps of uploading the appliance to a **supported virtualization or cloud provider.**" 
- I think it would be nice to specify RHV here for a better user experience as the guide specifically provides instructions on how to install and configure CloudForms on a Red Hat Virtualization environment.  We can probably look into this later as this applies to all installation guides, besides I think this chapter might also be in "common" for some of the installation guides.

Please let me know what you think. I think it's ready to be merged otherwise.

Thanks!
Suyog

**Comment by dayleparker** [comment]
Hi Suyog,

Thanks so much for your review and your feedback! I totally agree with your points above, and have changed:
* 1. updated OVF to OVA in those 3 instances (makes better sense!)
* 2. Changed the sentence to: "After downloading  Red Hat CloudForms as a virtual machine image template from the Red Hat Customer Portal, the installation process takes you through the steps of uploading the appliance to a Red Hat Virtualization environment. "

Good news -- that sentence is in the installation.adoc file so we can customize it per guide -- I'll make a bug to make this change for all the guides. I'm going to merge this myself as discussed, but I will leave the merging of the euwe and master PRs to you :)

Thanks so much,
Dayle

**Comment by suyogsainkar** [comment]
@dayleparker Awesome, thanks for making those changes, Dayle! I've merged https://github.com/ManageIQ/manageiq_docs/pull/261 and https://github.com/ManageIQ/manageiq_docs/pull/262 to their respective base branches. Cheers, Suyog

**Comment by dayleparker** [comment]
Thanks so much @suyogsainkar !

**Pull request merged**
