### PR TITLE
Add  minimum reqs for Google Compute Engine

### PR DESCRIPTION
**Pull request by FlorianOnmyown**
Add  minimum reqs for Google Compute Engine

### CODE REVIEW

**Comment by JPrause** [comment]
Thanks @FlorianOnmyown 
Will review this shortly.

**Comment by FlorianOnmyown** [comment]
@JPrause Great to hear that :)

**Comment by JPrause** [comment]
LGTM 👍 
@cybette can you have a look and merge if good.

**Comment by cybette** [comment]
Hi, I don't have merge rights for docs. Ping @ManageIQ/committers-documentation

**Comment by JPrause** [comment]
@cybette my bad,....been looking at manageiq.org all week. ha!

**Comment by Fryguy** [comment]
@adahms @cbudz Please review.

**Comment by JPrause** [comment]
@adahms @cbudz can you review and merge if all looks good.

**Comment by cbudz** [comment]
Looks good, @JPrause. Merging this request.

**Pull request merged**
