### PR TITLE
update general_configuration deleting downstream references

### PR DESCRIPTION
**Pull request by alexvkcr**
We were asked to create one pull request per file by  @sergio-ocon

But here we add 5 files because we think it's not necessary to create PRs for unmodified files.

As specified in the title, only creating_a_condition.adoc includes a modification.

The files included in this PR are:

defining_policies_and_profiles/topics/assigning_policy_profiles_to_a_cloud_provider.adoc
defining_policies_and_profiles/topics/assigning_policy_profiles_to_an_instance.adoc
defining_policies_and_profiles/topics/copying_a_condition.adoc
defining_policies_and_profiles/topics/copying_a_policy.adoc
defining_policies_and_profiles/topics/creating_a_condition.adoc

@CarlosGlez7 @katafira @delaluzparra

### CODE REVIEW

**Comment by sergio-ocon** [comment]
Great... I am refering to a document as defining_policies_and_profiles/, not individual input files

**Comment by alexvkcr** [comment]
Okey, we're turning each of the PRs uploaded already in a folder-specific PR.
We'll change the titles to facilitate work for everyone.
This PR is going to correspond to "/general_configuration"

We're uploading today a new PR which will correspond to a third folder.

**Comment by sergio-ocon** [comment]
Please use a title like "update general_configuration deleting downstream references"

**Comment by alexvkcr** [comment]
The word Red Hat appears multiple times in different contexts and refering to specific RH products. 

Left unmodified pending further instructions!

**Comment by Fryguy** [comment]
This one also has a busted history...I'm not sure if these are built off of a common branch or something, but there is a common problem with that first commit.

**Comment by chessbyte** [comment]
@alexvkcr what is the status of this PR?

**Comment by sergio-ocon** [comment]
There are new PR without the problem now to be updated.
We will provide the content as a basis for further work, as we can't own the content - we lack the capability to take decissions of what is there or not

**Comment by alexvkcr** [comment]
Closing PR because of busted history.

Changes added to PR #38

**Pull request closed without merging**
