### PR TITLE
Created a new article for Assigning a Custom CloudForms Analysis Prof…

### PR DESCRIPTION
**Pull request by suyogsainkar**
…ile to a VM

Hi Dayle,

I've created this article in Github in the required structure / formatting, and I've also included the image files. The content has been tech reviewed and I've incorporated the feedback items; plus added some further contextual info. Would you mind reviewing (and merging) the content to see if it reads and builds okay? Any feedback is welcome.

Many thanks!
Suyog

### CODE REVIEW

**Comment by dayleparker** [comment]
Hey Suyog,
The article looks really good! It builds fine, looks logically structured, and is easy to follow. As I read through it, I spotted a few places where the language could use a little tweaking, or an xref to another section might be helpful to the user. I can’t figure out how to comment on an individual topic, but I hope I’ve outlined my comments clearly here. Let me know if you need clarification, and also once you’re done with the feedback and are ready for a final review.

Cheers,
Dayle


Fix: In art-Assigning_Custom_Analysis_Profile_to_VM/cfme/docinfo.xml:

    The article title is missing “a” --> Assigning a Custom Analysis Profile to a Virtual Machine

In Preface:

    “… for specific virtual machine configurations or purposes using the Red Hat CloudForms user interface.” –> What kind of purposes? Is this in addition to specific VM configurations? If yes, would be good to provide more details, otherwise I’d recommend just removing “or purposes using the Red Hat CloudForms user interface.”
    Suggestion: Combine/shorten the following two sentences, as they seem to make similar points: "The procedure consists of creating a custom virtual machine analysis profile and assigning it to a virtual machine via a control policy. This document describes the steps required to assign a custom analysis profile to a virtual machine for use with SmartState analysis. "
        Perhaps something like (feel free to reword - I’m not sure control policy even needs mentioning here): This document describes the steps required to assign a custom analysis profile to a virtual machine for use with SmartState analysis.
    Fix: step 2. Creating an Action to Assign Profile to Analysis Task –> Is missing a few words - “Creating an Action to Assign a Profile to the Analysis Task” ?

In art-Assigning_Custom_Analysis_Profile_to_VM/topics/To_create_VM_analysis_profile.adoc

    In other docs, we mark up “admin” --> admin
    Mark up * as it’s keyboard input --> "type * in Registry Value. "
    In step 8, I think this sentence could be removed, as it’s explained in the previous sentence: “In that case, you do not need to know the registry value to collect the keys.”
    The markup in this line needs updating: In the Event Log tab, enter Name, Filter Message, Level, Source, and # (Number) of Days.

In …g_Custom_Analysis_Profile_to_VM/topics/To_add_assign_profile_to_analysis_task_action.adoc

    Chapter title is missing “a” and “an” --> Creating an Action to Assign a Profile to an Analysis Task
    Comment - the opening paragraph has a lot of important points, but I would suggest combining some of the sentences to make the language flow. ie. "Red Hat CloudForms contains a set of default actions, but you can also create custom actions using the CloudForms user interface. "
    Suggestion: Could this be an xref? (created in Creating a Virtual Machine Analysis Profile).
    Fix: “Step 2. Expand the Actions accordion, click” --> I think it should be “and click”
    Fix: "Select Assign Profile to Analysis Task from Action Type list. " --> "Select Assign Profile to Analysis Task from the Action Type list. " (missing “the”). Same in step 5. --> "from the Analysis Profiles list. "

In art-Assigning_Custom_Analysis_Profile_to_VM/topics/To_create_VM_control_policy.adoc

    Suggestion: In Step 16, could we add an xref? "select the action created in Creating an Action to Assign Profile to Analysis Task "
    Question: In step 16, should this be “conditions”? "This action will take place if the resources meet the condition of the policy. "
    Suggestion (in Note) - minor adjustments: “Each selected action can be executed synchronously or asynchronously; a synchronous action will not start until the previous synchronous action is completed, while an asynchronous action allows the next action to start whether or not the first action has completed.”
    Question (from Note) - I’m not sure what a trap is. Is this a common CloudForms term?
    Step 17 questions - should “(S) Synchronous” be marked up? Is it a GUI label? Also, “(Set selected Actions to Asynchronous)” and “(Set selected Actions to Synchronous)” are two different options, right? Could use clarifying. Also, is there a UI button image missing, or should the brackets go?

In _Analysis_Profile_to_VM/topics/To_create_policy_profile_and_assign_VM_control_policy.adoc

    Suggestion - add an xref for to the procedure mentioned for easier navigation.
    Fix: step 3 missing a word: --> "In the Basic Information area, enter a Description for the policy profile. "
    Step 4 - again, an xref would be good here. I’d also remove a few commas, for example: "Under Policy Selection, select the virtual machine control policy created in Creating a Virtual Machine Control Policy from Available Policies list. "

In art-Assigning_Custom_Analysis_Profile_to_VM/topics/To_assign_policy_profile_to_VM.adoc

    Suggestion: "all hosts / virtual machines " --> I’d lean towards replacing / with “or” so it’s more clear for the translation team.

**Comment by suyogsainkar** [comment]
@dayleparker Hi Dayle, thanks for your review and suggestions! I've incorporated those items into the respective sections. 

Btw, for procedural actions involving UI menus, buttons/lists etc., thought we were discarding articles prefixing the UI menu names. (for example: Select *option* from *xyz* list) as a UX/minimalism principle? Perhaps, worth revisiting the topic/discussion to avoid inconsistencies.

Cheers,
Suyog

**Comment by dayleparker** [comment]
Hi @suyogsainkar Thanks for making the edits -- looks great.  
Agreed, it would be good to discuss our format as a team for things like "Select _option_ from _xyz_ list" --> perhaps we could even go further and eliminate the word "list", which would make it read better grammatically as well. Let's discuss in our next meeting -- it would be good to be more consistent across all the docs!

Cheers,  
Dayle

**Comment by suyogsainkar** [comment]
@dayleparker Hi Dayle,
Sure - let's discuss in our next meeting. Thanks again for reviewing and merging the content!
Cheers,
Suyog

**Pull request merged**
