### PR TITLE
Bz1403111 chargebacklimits

### PR DESCRIPTION
**Pull request by dayleparker**
Hi Chris,

This is ready for your review.
I've made a few changes to the chargeback section for this BZ (was a bit of a combined 4.2/4.1 effort here -- this is the 4.2 PR.

Changes:

* Added a note about the container chargeback limitations listed in comment 1 & 3.

* From Comment 4 - Noted the missing assignment for containers providers (Labeled Images) to "5.3.1. Configuring Chargeback for Compute"  (Selected Containers Providers, Tagged Images already documented. Added Labeled Images.)

* Added procedures to "5.2. Creating Chargeback Rates" on editing and copying chargeback rates, as it seemed to be missing.

*  Added a note about Default Container Images to "5.3. Assigning Chargeback Rates" as it seemed to be the best place to mention it, and Loic's example illustrated how/why to use this very well. I don't think we often take this approach in our docs, but I thought it might work in this case. What do you think?

Preview:
http://file.bne.redhat.com/~dayparke/CloudForms/Container-chargeback/build/tmp/en-US/html-single/

Thanks for reviewing!
Dayle

### CODE REVIEW

**Comment by cbudz** [comment]
Hi Dayle,

Only small correction is the **Save** feature that seems to replace **Add** to complete Editing a chargeback rate. 

Everything else looks good here based on the comments in the BZ. Not sure why, but certain items aren't showing up in the preview: Note in 5.3 and Edit & Copy procedures in 5.2.

-Chris

**Comment by dayleparker** [comment]
Hi Chris,

Thanks for reviewing and letting me know about the correction, and the issue with the preview (I suspect I uploaded an older build :( Apologies for that!).

I've fixed the Editing procedure so it says Save. Thanks for catching it! Please let me know if you spot any more issues.

New preview: http://file.bne.redhat.com/~dayparke/CloudForms/Container-chargeback-euwe-new/build/tmp/en-US/html-single/#editing_a_chargeback_rate

Cheers,
Dayle

**Comment by cbudz** [comment]
Hi Dayle,

Thanks for the change. I just verified with Andrew that I can go ahead and make minor changes like that in the future and was just about to edit the file myself. Will merge now. 

Thanks,
Chris

**Comment by dayleparker** [comment]
Thanks Chris! Yes, totally feel free to go in there anytime and make a correction if it's an easy fix for you :)

**Pull request merged**
