### PR TITLE
[EUWE] Removed duplicate content from the Diagnostics section. Also removed …

### PR DESCRIPTION
**Pull request by suyogsainkar**
…region and zone aware server roles from that section which are already covered and recently updated in section Server Roles, so linked to that.

Preview: http://file.bne.redhat.com/ssainkar/Red_Hat_CloudForms-4.2-General_Configuration-en-US.pdf

### CODE REVIEW

**Comment by dayleparker** [comment]
Just checking in -- I'm going to hold off reviewing this one until https://bugzilla.redhat.com/show_bug.cgi?id=1421839#c7 is resolved.

**Comment by dayleparker** [comment]
Hey @suyogsainkar, I think this PR can be closed, as https://github.com/ManageIQ/manageiq_docs/pull/382 now resolves this bug, right? Just checking in, but please feel free to close if that's correct.
Cheers,
Dayle

**Comment by suyogsainkar** [comment]
@dayleparker Hey Dayle, thanks for checking in. This PR was held off because we were waiting on https://bugzilla.redhat.com/show_bug.cgi?id=1421839#c7 for a related discussion on primary/secondary and active/active server configuration, which is now resolved. Based on the discussion in the bug, https://github.com/ManageIQ/manageiq_docs/pull/382 adds a note to make it clearer for the reader, however this PR https://github.com/ManageIQ/manageiq_docs/pull/315/ addresses other changes such as the removal of some duplicate content and other structural changes under Diagnostics. I've resolved the merge conflict, and merging this to euwe now since you are away on PTO. Cheers, Suyog

**Comment by suyogsainkar** [comment]
Combined all of these updates into a single PR to make changes in CF4.5: https://github.com/ManageIQ/manageiq_docs/pull/399

**Pull request merged**
